version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    environment:
      WHATSAPP_API_SOURCE_PHONE: ""
      WHATSAPP_API_APP_NAME: ""
      WHATSAPP_API_KEY: ""
      LOGGER_LEVEL: "debug"
    react:
      build:
        context: ./frontend
      ports:
        - 3000:3000
      volumes:
        - ./frontend:/app
      environment:
        REACT_APP_API_URL: "http://localhost:3000"
