version: '3.8'

services:
  fastapi:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      WHATSAPP_API_SOURCE_PHONE: ""
      WHATSAPP_API_APP_NAME: ""
      WHATSAPP_API_KEY: ""
      LOGGER_LEVEL: "debug"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      REACT_APP_API_URL: "http://localhost:8000"
    command: npm start
